### ISSUE TITLE
Add .stylelintrc.js icon

### ISSUE THREAD

**Issue by donniean** [mallowigi/a-file-icon-idea#105]
Hi, I found .stylelintrc.js has not an icon, but stylelint.config.js has an icon: 

```yaml
	Stylelint:
		icon: "stylelint"
		priority: 2
		match: [
			[/^\.stylelintrc(\.|$)/i, "medium-purple"]
			[/^stylelint\.config\.js$/i, "auto-yellow"]
			[/\.stylelint(ignore|cache)$/i, "dark-blue"]
		]
```

So, could author please add .stylelintrc.js ( and other stylelin files icon: https://stylelint.io/user-guide/configure ) icon ?
